const quotes = [
  "You’re doing better than you think.",
  "Keep going — your dreams are cheering for you!",
  "Every small step counts. Keep stepping.",
  "You’ve got this. Seriously.",
  "The best view comes after the hardest climb.",
  "Progress, not perfection.",
  "Believe in your journey.",
  "One step closer — and that's amazing.",
  "The fact that you're trying means you're winning.",
  "You’re building something beautiful.",
  "Today’s effort is tomorrow’s success.",
  "You are capable of incredible things.",
  "Keep moving — even tiny steps matter.",
  "You’re braver than you feel right now.",
  "Trust your pace. It’s perfect for you.",
  "Every effort you make matters.",
  "Don’t quit. Great things take time.",
  "You’re writing a story worth telling.",
  "Be proud of how far you’ve come.",
  "Keep aiming for the stars — you’re closer than ever.",
  "You’re stronger than any obstacle.",
  "One day, you’ll be so glad you kept going.",
  "Every dream starts exactly where you are.",
  "Let’s celebrate your courage today!",
  "Growth happens quietly — trust it.",
  "Keep building. You're making magic.",
  "Your future self is already proud.",
  "Every sunrise is a new beginning.",
  "You've got the heart of a champion.",
  "Courage looks good on you.",
  "Little steps create big dreams.",
  "Every action you take is an act of hope.",
  "Keep daring, keep dreaming.",
  "You're more powerful than your doubts.",
  "Trust yourself — you've made it this far.",
  "You don’t have to be perfect, just persistent.",
  "You were made for this.",
  "Your dreams chose you for a reason.",
  "Don’t rush the process. Good things are growing.",
  "Let your hope be bigger than your fear.",
  "You've already won half the battle by starting.",
  "It’s okay to take it one breath at a time.",
  "You are someone’s inspiration.",
  "Each step forward deserves a celebration.",
  "Your dreams are lucky to have you.",
  "You make hard work look easy.",
  "There’s magic in not giving up.",
  "The best is yet to come — keep building!",
  "You’re exactly where you need to be.",
  "Even slow progress is progress.",
  "Your energy creates your future.",
  "Every finish line was once invisible.",
  "Celebrate the courage it took to begin.",
  "Trust the journey — it’s shaping you.",
  "A little progress each day adds up.",
  "Believe in your ability to figure things out.",
  "Your story is unfolding beautifully.",
  "Small victories are still victories.",
  "Be gentle with yourself — you're doing enough.",
  "You are more than capable.",
  "Even tiny faith moves mountains.",
  "Stay patient. Trust the magic you’re making.",
  "What you’re doing today matters tomorrow.",
  "You are worthy of your wildest dreams.",
  "One day you'll look back and smile at this moment.",
  "Let today be another brick in your masterpiece.",
  "Trust your process, honor your pace.",
  "You are doing an incredible job.",
  "Stay steady. Stay bold.",
  "Big achievements are made from tiny actions.",
  "You are closer than you realize.",
  "Hope grows stronger when you nurture it.",
  "There's strength in every struggle.",
  "You shine brighter than your fears.",
  "Keep watering your dreams.",
  "You were born to make an impact.",
  "Courage doesn’t always roar — sometimes it whispers 'try again.'",
  "You’re doing the best you can — and that’s enough.",
  "Be proud of the quiet work you’re doing.",
  "Little by little becomes a lot.",
  "Stay focused — your future is bright.",
  "Keep going — you’re almost there!",
  "You’re worthy of the life you're building.",
  "It’s a good day to keep dreaming.",
  "You already have everything you need inside you.",
  "Be kind to yourself along the way.",
  "There’s no timeline — only your timeline.",
  "Trust GOD to make it happen.",
  "One brave step at a time.",
  "You’re becoming someone incredible.",
  "Keep the faith strong.",
  "Your journey matters — every step of it.",
  "Don’t give up — your dreams are counting on you.",
  "Keep believing. Keep moving.",
  "Your growth is something to celebrate.",
  "Each new day brings new chances.",
  "You are stronger than yesterday.",
  "Stay hopeful — you’re closer than ever.",
  "Your light is unstoppable.",
  "Keep dreaming, keep daring, keep doing."
]


